version: '3.4'

services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - orderservice
      - customerservice
      - bookservice
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "8080:8080"
  mongo: 
    image: mongo
    ports: 
      - 27017:27017
  orderservice:
    image: orderservice
    container_name: orderservice
    build:
      context: orders
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    links: 
      - mongo
  customerservice:
    image: customerservice
    container_name: customerservice
    build:
      context: customers
      dockerfile: ./Dockerfile
    environment: 
      NODE_ENV: development
    ports:
      - 4000:4000
    links:
      - mongo
  bookservice:
    image: bookservice
    container_name: bookservice
    build:
      context: books
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
    links:
      - mongo
